Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Configuración de recursos para todas las máquinas
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Definición de Nodos de Backend (A y B)
  {
    "nodo-a" => "192.168.56.20",
    "nodo-b" => "192.168.56.21"
  }.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip
      # Aprovisionamiento: Instalar LXD automáticamente
      node.vm.provision "shell", path: "scripts/setup_lxd.sh"
    end
  end

  # Definición de Balanceadores (LB1 y LB2)
  {
    "lb1" => "192.168.56.10",
    "lb2" => "192.168.56.11"
  }.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip
    end
  end
end